### ISSUE TITLE
Release 0.2?

### ISSUE THREAD

**Issue by Kris-LIBIS** [excpt/moments#14]
Can we get a new release, please? The updates and fixes you did last year are really worth having in a release.

**Comment by Kris-LIBIS** [comment]
Sorry, correction. There is a 0.2.0 release. I assumed it was not as I got an error that the 3rd parameter (mode) was not supported. Github only showed the 0.1.0 release, so I was a bit mislead. But still a 0.2.1 that includes the new mode parameter would be welcome.

**Comment by excpt** [comment]
This missing release 0.2.0 entry on GitHub is my fault. Fixing it.

New release is in the works.

**Comment by excpt** [comment]
Version 0.3.0 released.
