### ISSUE TITLE
Replace Travis CI with another CI

### ISSUE THREAD

**Issue by AlexWayfer** [excpt/moments#3]
Hello.

As I know, Travis CI is using old integration method with GitHub and may not work.

Also, I've faced with too many problems with it.

For example, I don't see somewhy checks of my PR (#2) and `master` after merging:

![image](https://user-images.githubusercontent.com/6510020/86466357-22ef0a80-bd3c-11ea-95d6-12f2372be9a7.png)

https://travis-ci.org/github/excpt/moments/builds

![image](https://user-images.githubusercontent.com/6510020/86466392-339f8080-bd3c-11ea-9e48-e57468188815.png)

Also similar discussion: https://github.com/tycooon/memery/issues/28

So, I suggest [Cirrus CI](https://cirrus-ci.org/guide/quick-start/): it's pretty compact and fast.

I can send a PR with it, if you want, but you have to enable an application in repository settings (give an access).

Or we can choose another CI.

**Comment by excpt** [comment]
I'll look into it this weekend. I think I have to fix all the CI settings.

I'll give you feedback on that.

**Comment by AlexWayfer** [comment]
OK, thank you.

**Comment by excpt** [comment]
@AlexWayfer this should be fixed now. :)

https://github.com/excpt/moments/compare/7dd28253f665...03b60b3e7aff

**Comment by AlexWayfer** [comment]
> @AlexWayfer this should be fixed now. :)

OK, thank you! Let's check it in #5
